name: relic_io
description: dart:io adapter for Relic web server.
version: 0.14.0
repository: https://github.com/serverpod/relic
homepage: https://docs.dartrelic.dev/
topics:
  - server
  - web
  - backend
  - http

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  crypto: ^3.0.0
  mime: ">=1.0.6 <3.0.0"
  path: ^1.8.3
  relic_core: ^0.14.0
  stack_trace: ^1.10.0
  stream_channel: ^2.1.1
  web_socket: ^1.0.1

dev_dependencies:
  lints: ">=5.0.0 <7.0.0"
  serverpod_lints: ^3.0.0
  test: ^1.25.10
  test_descriptor: ^2.0.1
  web_socket_channel: ^3.0.3
